[package]
name = "steelseries-core"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
publish = false

[dependencies]
hidapi.workspace = true
thiserror.workspace = true

[lints]
workspace = true

