#!/bin/sh
set -e

case "$1" in
    configure)
        if command -v udevadm >/dev/null 2>&1; then
            udevadm control --reload-rules >/dev/null 2>&1 || true
            udevadm trigger --subsystem-match=hidraw --action=change >/dev/null 2>&1 || true
        fi
        ;;
esac

#DEBHELPER#

exit 0
